version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/first-team-project-dev/
hooks:
  ApplicationStop:
    - location: /home/ubuntu/first-team-project-dev/scripts/application_stop.sh
      timeout: 300
      runas: ubuntu
  BeforeInstall:
    - location: /home/ubuntu/first-team-project-dev/scripts/before_install.sh
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: /home/ubuntu/first-team-project-dev/scripts/after_install.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: /home/ubuntu/first-team-project-dev/scripts/application_start.sh
      timeout: 300
      runas: ubuntu
  ValidateService:
    - location: /home/ubuntu/first-team-project-dev/scripts/validate_service.sh
      timeout: 300
      runas: ubuntu
