version: 0.0
os: linux
files:
  - source: target/*.jar
    destination: /home/ubuntu/first-team-project-dev
hooks:
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 300
      runas: ubuntu
