version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/build/
permissions:
  - object : /
    pattern: "**"
    owner: ubuntu
    group: ubuntu
hooks:
  AfterInstall:
    - location: after_install.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: application_start.sh
      timeout: 300
      runas: ubuntu
  ValidateService:
    - location: validate_service.sh
      timeout: 300
      runas: ubuntu
