version: 0.0
os: linux
files:
  - source: build/libs/*.jar
    destination: /home/ubuntu/first-team-project-dev
hooks:
  ApplicationStop:
    - location: scripts/application_stop.sh
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 300
      runas: ubuntu
