version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing dependencies...
      - chmod +x gradlew  # gradlew에 실행 권한 추가
  build:
    commands:
      - echo Building the project...
      - ./gradlew build -x test  # 테스트 제외하고 빌드
  post_build:
    commands:
      - echo Build completed
      - ls build/libs
artifacts:
  files:
    - build/libs/*.jar
    - appspec.yml
    - scripts/**
  discard-paths: yes
